name: Discloud Auto Deploy

on:
  push:
    branches:
     - github

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Discloud
        uses: discloud/action-deploy@v1.2.2
        with:
          token: ${{ secrets.DISCLOUD_TOKEN }}
